#!/usr/bin/env bash
# scripts/regen-seccomp.sh — regenerate packaging/seccomp/witness.json
#
# Runs the witness daemon under strace for DURATION seconds, collects all
# observed syscall names, and writes an OCI-format seccomp allowlist.
#
# Requirements: strace, jq, witness binary in PATH or at $WITNESS_BIN
#
# Usage:
#   sudo ./scripts/regen-seccomp.sh            # default 60s observation window
#   sudo ./scripts/regen-seccomp.sh 120        # 120s observation window
#
# The resulting packaging/seccomp/witness.json is a reference profile.
# Commit it after review. Systemd hardening uses SystemCallFilter (in the
# .service file) rather than this JSON — but both should stay consistent.
#
# WARNING: Wider observation windows catch more rare syscalls. Do not shorten
# below 30s — the Go runtime uses several syscalls only on GC or timer events.

set -euo pipefail

DURATION="${1:-60}"
WITNESS_BIN="${WITNESS_BIN:-$(command -v witness 2>/dev/null || echo '')}"
OUTFILE="$(dirname "$0")/../packaging/seccomp/witness.json"
TMPDIR_RUN=$(mktemp -d)
STRACE_LOG="$TMPDIR_RUN/strace.log"

cleanup() { rm -rf "$TMPDIR_RUN"; }
trap cleanup EXIT

# ── Preflight ─────────────────────────────────────────────────────────────────
if [[ -z "$WITNESS_BIN" ]]; then
    echo "ERROR: 'witness' binary not found. Set WITNESS_BIN or put it in PATH." >&2
    exit 1
fi
command -v strace >/dev/null 2>&1 || { echo "ERROR: strace not installed." >&2; exit 1; }
command -v jq    >/dev/null 2>&1 || { echo "ERROR: jq not installed." >&2; exit 1; }
[[ "$(id -u)" -eq 0 ]] || { echo "ERROR: run as root (strace requires it for attach)." >&2; exit 1; }

echo "[regen-seccomp] Observation window: ${DURATION}s"
echo "[regen-seccomp] Witness binary:     $WITNESS_BIN"
echo "[regen-seccomp] Strace log:         $STRACE_LOG"

# ── Run witness under strace ──────────────────────────────────────────────────
# -ff: follow forks into separate log files (Go spawns goroutines as threads)
# -e trace=all: capture every syscall
# -o: per-thread log prefix
strace -ff -e trace=all -o "$STRACE_LOG" "$WITNESS_BIN" start &
WITNESS_PID=$!

echo "[regen-seccomp] Witness PID: $WITNESS_PID (observing for ${DURATION}s)"
sleep "$DURATION"

kill -TERM "$WITNESS_PID" 2>/dev/null || true
wait "$WITNESS_PID" 2>/dev/null || true

# ── Collect syscall names ─────────────────────────────────────────────────────
# strace -ff writes to STRACE_LOG.<pid>; collect all of them.
# Each line looks like: open("...", O_RDONLY) = 3
SYSCALLS=$(grep -h '^[a-z_]' "$STRACE_LOG".* 2>/dev/null \
    | sed 's/([^)]*).*//' \
    | sort -u)

SYSCALL_ARRAY=$(echo "$SYSCALLS" | jq -R . | jq -s .)

# ── Write OCI seccomp JSON ────────────────────────────────────────────────────
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

jq -n \
    --argjson syscalls "$SYSCALL_ARRAY" \
    --arg ts "$TIMESTAMP" \
    '{
      "_comment": ("OCI/Docker-format seccomp allowlist for the Witness daemon. Generated by scripts/regen-seccomp.sh at " + $ts + ". Do not edit by hand."),
      "defaultAction": "SCMP_ACT_ERRNO",
      "defaultErrnoRet": 1,
      "architectures": ["SCMP_ARCH_X86_64", "SCMP_ARCH_AARCH64"],
      "syscalls": [
        {
          "names": $syscalls,
          "action": "SCMP_ACT_ALLOW",
          "comment": ("observed over " + $ts + " run")
        }
      ]
    }' > "$OUTFILE"

echo "[regen-seccomp] Wrote $(echo "$SYSCALLS" | wc -l | tr -d ' ') syscalls → $OUTFILE"
echo "[regen-seccomp] Review the diff before committing:"
echo "  git diff packaging/seccomp/witness.json"
